version: '3'
services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: .
      dockerfile: ./.devcontainer/backend-container/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - frontend
    ports:
      - "8000:8000"

  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: .
      dockerfile: ./.devcontainer/frontend-container/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "8080:8080"
