# Generated by Django 5.1.2 on 2024-11-04 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug_name",
                    models.CharField(
                        choices=[("gpt-4o", "Gpt 4O"), ("gpt-4o-mini", "Gpt 4O Mini")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                (
                    "slug_provider",
                    models.CharField(
                        choices=[("azure-openai", "Azure Open Ai")], max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("configuration", models.JSONField()),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conversations.aimodel",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(blank=True, null=True, to="users.user"),
                ),
            ],
        ),
    ]
