# Generated by Django 5.1.2 on 2024-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="slug_provider",
            field=models.CharField(
                choices=[("azure-openai", "Azure Open Ai")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="chatevents",
            name="type",
            field=models.CharField(
                choices=[
                    ("human_message", "Human Message"),
                    ("ai_message", "Ai Message"),
                    ("function_message", "Function Message"),
                ],
                max_length=50,
            ),
        ),
    ]
