# Generated by Django 5.1.3 on 2024-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="slug_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
