# Generated by Django 5.1.2 on 2024-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_alter_aimodel_slug_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="slug_provider",
            field=models.CharField(
                choices=[("azure-openai", "Azure Open Ai"), ("openai", "Open Ai")],
                max_length=50,
            ),
        ),
    ]
