# Generated by Django 5.1.2 on 2024-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_alter_aimodel_slug_provider_alter_chatevents_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="slug_name",
            field=models.CharField(
                choices=[("gpt-4o", "Gpt 4O"), ("gpt-4o-mini", "Gpt 4O Mini")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
