# Generated by Django 5.1.2 on 2025-05-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_alter_aimodel_slug_provider"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="users",
            field=models.ManyToManyField(blank=True, to="users.user"),
        ),
    ]
