[project]
dependencies = [
  "django-extensions>=3.2.3",
  "django-ninja>=1.3.0",
  "django>=5.1.2",
  "langchain>=0.3.6",
  "ruff>=0.7.1",
]
name = "backend"
requires-python = ">=3.12"
version = "0.1.0"
